title: Taiki Hagiwara
description: Game programmer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://taikihagiwara.com/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title.html

# Author settings
author: Taiki Hagiwara # add your name

# Contact links
email: thagiwarapro@gmail.com # Add your Email address
linkedin: taiki-jl-hagiwara # Add your Linkedin handle
github: TaikiJL # Add your Github handle
twitter: BigTree9292

# Paginate
#paginate: 6
#paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
