# Site settings
title: Taiki Hagiwara
email: thagiwarapro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  © 2016 Taiki Hagiwara
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://taikijl.github.io/"
#twitter_username: jekyllrb
github_username:  TaikiJL

# Build settings
markdown: kramdown
